name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      database_hostname: ${{ secrets.DATABASE_HOSTNAME }}
      database_port: ${{ secrets.DATABASE_PORT }}
      database_password: ${{ secrets.DATABASE_PASSWORD }}
      database_name: ${{ secrets.DATABASE_NAME }}
      database_username: ${{ secrets.DATABASE_USERNAME }}
      secret_key: ${{ secrets.SECRET_KEY }}
      algorithm: ${{ secrets.ALGORITHM }}
      access_token_expire_minutes: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create test database
        run: |
          PGPASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          psql -h localhost -U ${{ secrets.DATABASE_USERNAME }} -d postgres \
          -c "CREATE DATABASE \"${{ secrets.DATABASE_NAME }}_test\";"

      - name: Run tests
        run: |
          pytest tests/

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/blogapi:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: |
          echo "Deploying to server..."